apiVersion: v1
kind: Template
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: index-recent
      labels:
        jobgroup: indexing
    spec:
      template:
        metadata:
          name: index-recent
          labels:
            jobgroup: indexing
        spec:
          containers:
          - name: c
            image: eu.gcr.io/kbh-billeder/frontend:$(BRANCH)-latest
            imagePullPolicy: Always
            command: ["npm", "run", "index", "recent"]
          restartPolicy: Never
parameters:
  - name: BRANCH
    description: The branch from which the image should be derived
    required: true
