version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4.5
    container_name: elasticsearch
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200
    networks:
      - esnet
  mongo:
    image: 'mongo:3.5.6'
    container_name: mongodb
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'

volumes:
  esdata:
    driver: local

networks:
  esnet:
