# template is outdated - don't use this to update the cron deployment!
# - ath88

apiVersion: v1
kind: Template
objects:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: cron
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            component: cron
        spec:
          containers:
          - name: cron
            image: blacklabelops/jobber:cloud
            imagePullPolicy: Always
            resources: {}
            env:
            - name: KBH_ACCESS_KEY
              value: NOT-THE-ACTUAL-KEY
            - name: JOB_NAME1
              value: "Incremental"
            - name: JOB_COMMAND1
              value: "curl 'https://$(FRONTEND_PUBLIC_HOSTNAME)/index/recent?timeframe=70m&accesskey=$(KBH_ACCESS_KEY)'"
            - name: JOB_TIME1
              value: "$(INCREMENTAL_TIMING)"
            - name: JOB_NAME2
              value: "Full"
            - name: JOB_COMMAND2
              value: "curl 'https://$(FRONTEND_PUBLIC_HOSTNAME)/index/all?accesskey=$(KBH_ACCESS_KEY)'"
            - name: JOB_TIME2
              value: "$(FULL_TIMING)"
parameters:
  - name: FRONTEND_PUBLIC_HOSTNAME
    description: The public hostname of the frontend
    required: true
  - name: INCREMENTAL_TIMING
    description: Jobber timing configuration for incremental jobs
    required: true
  - name: FULL_TIMING
    description: Jobber timing configuration for full jobs
    required: true
