apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kbh-billeder
  labels:
    stage: beta
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        component: frontend
    spec:
      containers:
      - name: frontend
        image: eu.gcr.io/kbh-billeder/frontend:latest
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: ES_HOST
          value: "127.0.0.1:9200"
      - name: es
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:2.3.2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "kbh-billeder-es-cluster"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
