apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: elasticsearch
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            component: elasticsearch
        spec:
          containers:
          - name: elasticsearch
            securityContext:
              capabilities:
                add:
                  - IPC_LOCK
            # ES is doing some stuff with ulimit that requires this
                  - SYS_RESOURCE
              privileged: true
            image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.4
            # Ensure max_map_count is bumped before we start ES.
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144 && /run.sh']
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "CLUSTER_NAME"
              value: "kbh-billeder-es-cluster"
            - name: "DISCOVERY_SERVICE"
              value: "elasticsearch"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_DATA
              value: "true"
            - name: HTTP_ENABLE
              value: "true"
            - name: NETWORK_HOST
              value: "_local_,_site_"
            ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
            volumeMounts:
            - mountPath: /data
              name: es-storage
          volumes:
          - name: es-storage
            gcePersistentDisk:
              pdName: $(ES_DISK_NAME)
              fsType: ext4
parameters:
  - name: ES_DISK_NAME
    description: The name of the elasticsearch disk
    required: true
