# Defines an ingress load-balancer for the frontend-services.
#
apiVersion: v1
kind: Template
objects:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: frontend-ingress
      annotations:
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "gce"
        kubernetes.io/ingress.global-static-ip-name: $(FRONTEND_PUBLIC_IP_NAME)
        ingress.kubernetes.io/ssl-redirect: "true"

    spec:
      tls:
      - hosts:
        - $(FRONTEND_PUBLIC_HOSTNAME)
        secretName: frontend-certificate
      backend:
        serviceName: frontend
        servicePort: 80
      rules:
      - host: $(FRONTEND_PUBLIC_HOSTNAME)
        http:
          paths:
          - path: /*
            backend:
              serviceName: frontend
              servicePort: 80
parameters:
  - name: FRONTEND_PUBLIC_HOSTNAME
    description: The public hostname of the frontend
    required: true
  - name: FRONTEND_PUBLIC_IP_NAME
    description: Named static ip
    required: true
