apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: frontend
      labels:
        component: frontend
    spec:
      type: LoadBalancer
      loadBalancerIP: $(FRONTEND_PUBLIC_IP)
      sessionAffinity: ClientIP
      selector:
        component: frontend
      ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP
parameters:
  - name: FRONTEND_PUBLIC_IP
    description: The public static IP of the frontend
    required: true
