apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 146.148.22.138
  selector:
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
