apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  type: LoadBalancer
  selector:
    component: frontend
  ports:
  - name: http
    port: 9000
    protocol: TCP
