apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
  labels:
    stage: beta
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
          name: http
          protocol: TCP
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
      - name: mongo-storage
        gcePersistentDisk:
          pdName: mongo-disk
          fsType: ext4
