apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: $(NAMESPACE)
parameters:
  - name: NAMESPACE
    description: The Kubenetes namespace
    value: default
    required: true
