apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  type: LoadBalancer
  selector:
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  - name: es-http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
